services:
  proxy:
    build: 
      context: proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on: 
      - web
      - app

  web:
    build: 
      context: web
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./web:/app
      - astro_node_modules:/app/node_modules
    ports:
      - 4321:4321
    depends_on:
      - app

  app:
    build:
      context: flask
      dockerfile: Dockerfile
    stop_signal: SIGINT  # flask requires SIGINT to stop gracefully, just sayin'
    restart: always
    environment:
      - FLASK_SERVER_PORT=9091
      - PYTHONUNBUFFERED=0
      - PYTHONPATH=/src
    volumes:
      - ./flask:/src


volumes:
  astro_node_modules:
