services:
  proxy:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - astro_build:/usr/share/nginx/html
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    entrypoint: "/bin/sh -c 'nginx && while true; do nginx -s reload; sleep 12h; done'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - proxy
    entrypoint: "/bin/sh -c 'while true; do certbot renew; sleep 12h; done'"

  web:
    build:
      dockerfile: Dockerfile.prod
    volumes:
      - astro_build:/app

  app:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - FLASK_SERVER_PORT=9091
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/src
    volumes:

volumes:
  astro_node_modules:
  astro_build:
